smartsnippets/models.py
from django.core.cache import cache
from django.db import models
from django.core.exceptions import ValidationError
from django.template import Template, TemplateSyntaxError, \
    TemplateDoesNotExist, loader
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin

from .settings import snippet_caching_time, caching_enabled


class SmartSnippet(models.Model):
    name = models.CharField(unique=True, max_length=255)
    template_code = models.TextField(_("Template code"), blank=True)
    template_path = models.CharField(
        _("Template path"),
        max_length=100, blank=True,
        help_text=_(
            'Enter a template (i.e. "snippets/plugin_xy.html")'
            ' which will be rendered.'))
    sites = models.ManyToManyField(
        Site, null=False, blank=True,
        help_text=_('Select on which sites the snippet will be available.'),
        verbose_name='sites')
    description = models.TextField(_("Description"), blank=True)
    documentation_link = models.CharField(
        _("Documentation link"),
        max_length=100, blank=True,
        help_text=_('Enter URL (i.e. "http://snippets/docs/plugin_xy.html")'
                    ' to the extended documentation.'))

    class Meta:
        ordering = ['name']
        verbose_name = 'Smart Snippet'
        verbose_name_plural = 'Smart Snippets'

    def __init__(self, *args, **kwargs):
        #hack due to
        #     https://code.djangoproject.com/ticket/16433#no1
        for rel_obj in self._meta.get_all_related_objects():
            rel_obj.help_text = ""
        super(SmartSnippet, self).__init__(*args, **kwargs)

    def get_template(self):
        if self.template_path:
            return loader.get_template(self.template_path)
        else:
            return Template(self.template_code)

    def clean_template_code(self):
        try:
            self.get_template()
        except (TemplateSyntaxError, TemplateDoesNotExist), e:
            raise ValidationError(str(e))

    def get_cache_key(self):
        return 'smartsnippet-%s' % self.pk

    def render(self, context):
        return self.get_template().render(context)

    def __unicode__(self):
        return self.name


class SmartSnippetVariable(models.Model):
    name = models.CharField(
        max_length=50,
        help_text=_('Enter the name of the variable defined in '
                    'the smart snippet template.'))
    widget = models.CharField(
        max_length=50,
        help_text=_('Select the type of the variable defined '
                    'in the smart snippet template.'))
    snippet = models.ForeignKey(SmartSnippet, related_name="variables")

    class Meta:
        unique_together = (('snippet', 'name'))
        ordering = ['name']
        verbose_name = "Standard variable"

    def save(self, *args, **kwargs):
        super(SmartSnippetVariable, self).save(*args, **kwargs)
        smartsnippet_pointers = self.snippet.smartsnippetpointer_set.all()
        for spointer in smartsnippet_pointers:
            v, _ = Variable.objects.get_or_create(snippet=spointer,
                                                  snippet_variable=self)
            v.save()

    def __unicode__(self):
        return self.name


class SmartSnippetPointer(CMSPlugin):
    snippet = models.ForeignKey(SmartSnippet)

    def get_cache_key(self):
        return 'smartsnippet-pointer-%s' % self.pk

    def render(self, context):
        cache_key = self.get_cache_key()
        user = context['request'].user
        if not user.is_staff and caching_enabled and cache.has_key(cache_key):
            return cache.get(cache_key)
        vars = dict((var.snippet_variable.name, var.formatted_value)
                    for var in self.variables.select_related('snippet_variable').all())
        context.update(vars)
        rendered_snippet = self.snippet.render(context)
        if not user.is_staff and caching_enabled:
            cache.set(cache_key, rendered_snippet, snippet_caching_time)
        return rendered_snippet

    def copy_relations(self, old_instance):
        for variable in old_instance.variables.all():
            variable.pk = None
            variable.snippet = self
            variable.save()

    def __unicode__(self):
        return unicode(self.snippet)


class Variable(models.Model):
    snippet_variable = models.ForeignKey(SmartSnippetVariable,
                                         related_name='variables')
    value = models.TextField()
    snippet = models.ForeignKey(SmartSnippetPointer, related_name='variables')

    class Meta:
        unique_together = (('snippet_variable', 'snippet'))

    @property
    def formatted_value(self):
        from widgets_pool import widget_pool
        widget_instance = widget_pool.get_widget(self.snippet_variable.widget)(self)
        return widget_instance.formatted_value

    @property
    def name(self):
        return self.snippet_variable.name

    @property
    def widget(self):
        return self.snippet_variable.widget


class DropDownVariable(SmartSnippetVariable):
    choices = models.CharField(
        max_length=512,
        help_text=_(
            'Enter a comma separated list of choices that will be '
            'available in the dropdown variable when adding and '
            'configuring the smart snippet on a page.'))

    @property
    def choices_list(self):
        return ([choice.strip() for choice in self.choices.split(',') if choice.strip()]
                if self.choices else [])

    def save(self, *args, **kwargs):
        self.widget = 'DropDownField'
        super(DropDownVariable, self).save(*args, **kwargs)

smartsnippets/views.py
# Create your views here.

smartsnippets/templates/smartsnippets/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify staticfiles %}
{% load url from future %}

{% block extrahead %}{{ block.super }}
{% url 'admin:jsi18n' as jsi18nurl %}
<script type="text/javascript" src="{{ jsi18nurl|default:"../../../jsi18n/" }}"></script>
<script type="text/javascript" src="{{ STATIC_URL}}admin/js/codemirror/codemirror.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}admin/js/codemirror/javascript.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}admin/js/codemirror/css.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}admin/js/codemirror/xml.js"></script>
<script type="text/javascript" src="{{ STATIC_URL}}admin/js/CMInstance.js"></script>

<script type="text/javascript" src="{{ STATIC_URL}}admin/js/codemirror/htmlmixed.js"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/codemirror.css' %}" />
{% endblock %}


{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
     {% if has_change_permission %}<a href="../">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %} &rsaquo;
     {% if add %}{% trans "Add" %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endif %}{% endblock %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li><a href="history/" class="historylink">{% trans "History" %}</a></li>
    {% if has_absolute_url %}<li><a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif%}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.module_name }}_form">{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
{% if save_on_top %}{% submit_row %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% blocktrans count errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% for fieldset in adminform %}
  {% include "smartsnippets/fieldset.html" %}
{% endfor %}

{% block after_field_sets %}{% endblock %}

{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}

{% block after_related_objects %}{% endblock %}

{% if read_only %}
<div class="submit-row">
    <a style="float:right; padding:10px" href="../">Back to Smart Snippets</a>
</div>
{% else %}
    {% submit_row %}
{% endif %}

{% if adminform and add %}
   <script type="text/javascript">document.getElementById("{{ adminform.first_field.id_for_label }}").focus();</script>
{% endif %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>

{% endblock %}

smartsnippets/templates/smartsnippets/fieldset.html
<fieldset class="module aligned {{ fieldset.classes }}">
    {% if fieldset.name %}<h2>{{ fieldset.name }}</h2>{% endif %}
    {% if fieldset.description %}
        <div class="description">{{ fieldset.description|safe }}</div>
    {% endif %}
    {% for line in fieldset %}
        <div class="form-row{% if line.fields|length_is:'1' and line.errors %} errors{% endif %}{% for field in line %} {{ field.field.name }}{% endfor %}">
            {% if line.fields|length_is:'1' %}{{ line.errors }}{% endif %}
            {% for field in line %}
                <div{% if not line.fields|length_is:'1' %} class="field-box{% if not field.is_readonly and field.errors %} errors{% endif %}"{% endif %}>
                    {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
                    {% if field.is_checkbox %}
                        {{ field.field }}{{ field.label_tag }}
                    {% else %}
                        {{ field.label_tag }}
                        {% if field.is_readonly %}
                                {% if field.field.name == "template_code" %}
                                        <textarea id='template_preview'>{{ field.contents }}</textarea>
                                        <script type="text/javascript">
                                            new CMInstance(django.jQuery('#template_preview')[0])
                                        </script>
                                {% else %}
                                       <p>{{ field.contents }}</p>
                                {% endif %}
                        {% else %}
                                {{ field.field }}
                                {% if field.field.name == "template_code" %}
                                    <script type="text/javascript">
                                        new CMInstance(django.jQuery('#id_template_code')[0],
                                            {
                                                readOnly: false
                                            },
                                            [{
                                                name: "change",
                                                handler: function(target){
                                                    django.jQuery('#id_template_code')[0].value = target.getValue();
                                                    if(typeof django.jQuery.updateSnippetVars === 'function'){
                                                        django.jQuery.updateSnippetVars(django.jQuery('#id_template_code')[0])
                                                    }
                                                }
                                            }])
                                    </script>
                                {% endif %}
                                
                        {% endif %}
                     {% endif %}
                     {% if field.field.help_text and not field.is_readonly %}
                        <p class="help">{{ field.field.help_text|safe }}</p>
                     {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</fieldset>

smartsnippets/templates/smartsnippets/plugin.html
{{content|safe}}

smartsnippets/templates/smartsnippets/plugin_change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify cms_admin staticfiles %}

{% block extrahead %}
<script type="text/javascript">
var current_site = {{current_site}};
</script>
{{ block.super }}
<script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}

<script type="text/javascript">
//<![CDATA[
(function($) {
	function runOnLoad(f) {
		if (runOnLoad.loaded){
			f();
		}else{
			runOnLoad.funcs.push(f);
		}
	}
	runOnLoad.funcs = [];
	runOnLoad.loaded = false;
	runOnLoad.run = function() {
		if (runOnLoad.loaded) return;

		for(var i = 0; i < runOnLoad.funcs.length; i++) {
			try {
				runOnLoad.funcs[i]();
			}catch(e) { }
		}
		runOnLoad.loaded = true;
		delete runOnLoad.funcs;
		delete runOnLoad.run;
	};
	if (window.addEventListener){
		window.addEventListener("load", runOnLoad.run, false);
	}else if (window.attachEvent){
		window.attachEvent("onload", runOnLoad.run);
	}else{
		window.onload = runOnLoad.run;
	}
	runOnLoad(function(){
		parent.setiframeheight($('body').height()+20, {{ plugin.pk }});
	});
	$(document).ready(function(){
		$("a.add-another,a.related-lookup").each(function(i, sign){
			var href = $(sign).attr("href")
			if (href.substr(0,2) == ".."){
				href = "../../"+href
				$(sign).attr("href", href);
			}
		});
	});
})(jQuery);
//]]>
</script>


{% endblock %}

{% block extrastyle %}<link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}" />{% endblock %}

{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}

{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../">{{ app_label|capfirst|escape }}</a> &rsaquo;
     {% if has_change_permission %}<a href="../">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %} &rsaquo;
     {% if add %}{% trans "Add" %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endif %}{% endblock %}

{% block content_title %}<h2>{{ plugin.get_plugin_name }}</h2>{% endblock %}

{% block content %}<div id="content-main">
{% block top %}{% if preview %}{% render_plugin plugin %}{% endif %}{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.module_name }}_form">{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="_popup" value="1" />{% endif %}
{% if current_site %}<input type="hidden" name="_current_site" value="{{current_site}}" />{% endif %}
{% if save_on_top %}{% submit_row %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% blocktrans count errors|length as counter %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
    <ul class="errorlist">{% for error in adminform.form.non_field_errors %}<li>{{ error }}</li>{% endfor %}</ul>
{% endif %}

{% block fieldsets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}

{% block after_related_objects %}{% endblock %}


{% if add %}
   <script type="text/javascript">document.getElementById("{{ adminform.first_field.auto_id }}").focus();</script>
{% endif %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
<span class="plugin-submit-row"{% if is_popup %} style="overflow: auto;"{% endif %}>
	<input type="submit" name="_save" class="default" value="{% trans "Save" %}" {{ onclick_attrib }}/>
	<input type="submit" style="margin-left: 8px;" value="{% trans "Cancel" %}" name="_cancel" class="cancel-btn">
</span>
</form>

</div>
{% endblock %}

smartsnippets/templates/smartsnippets/snippet_change_form.html
{% extends "smartsnippets/plugin_change_form.html" %}
{% load smartsnippets_tags %}


{% if original.snippet.description or original.snippet.documentation_link%}
    {% block extrahead %}
        {{ block.super }}
        <style>
            span.plugin-help-tooltip{
                cursor: help;
            }
            .plugin-help-tooltip{
                float: left;
                margin-right: 5px;
            }
            .plugin-help-tooltip img{
                border: 0;
                width: 20px;
                height: 20px;
            }

            #layout_help_popup{
                position: absolute;
                top:0;
                margin:0 auto;
            }
        </style>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/tipTip.css" />
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tipTip.minified.js"></script>
        <script type="text/javascript">
        //<![CDATA[
        (function($) {


            $(document).ready(function(){
                $(".plugin-help-tooltip").tipTip({maxWidth: "250px", delay: 100});
                
            });
        })(jQuery);
        //]]>
        </script>
        <script type="text/javascript">
          var in_admin = true;
        </script>
    {% endblock %}
{% endif %}

{% block content_title %}
{% if original.snippet.documentation_link %}
    <a class="plugin-help-tooltip" href='{{original.snippet.documentation_link}}' target='_blank' title='{% if original.snippet.description %}{{original.snippet.description}}<br/><br/>{% endif %}Follow link to see documentation'><img src="{{STATIC_URL}}images/help.png"></a>
{% elif original.snippet.description %}
    <span class="plugin-help-tooltip" title='{{original.snippet.description}}'><img src="{{STATIC_URL}}images/help.png"></span>
{% endif %}
{{ block.super }}
{% endblock%}

{% block top %}
<div style="padding:10px; margin-bottom: 10px; border:1px solid #ccc">
<h3>Preview:</h3>
<hr/><br/>
{{ block.super }}
</div>
{% endblock %}

{% block after_related_objects %}
{{ block.super }}
{% if variables %}
    <fieldset class="module">
        <h2>Smart Snippet Variables</h2>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
            {% for variable in variables %}
                {% render_variable variable %} 
            {% endfor %}
            </tbody>
        </table>
    </fieldset>
{% endif %}

{% endblock %}

smartsnippets/templates/smartsnippets/widgets/dropdownfield/widget.html
<tr>
    <td><label for="var_{{ field.name }}">{{ field.name }}</label></td>
    <td>
        <select id="var_{{ field.name }}" name="_{{ field.name }}_">
            <option value="">---------</option>
            {% for value in field.snippet_variable.dropdownvariable.choices_list %}
                <option {% if value == field.value %} selected="selected" {% endif %} value="{{ value }}" >{{ value }}</option>
            {% endfor %}
        </select>
    </td>
</tr>

smartsnippets/templates/smartsnippets/widgets/textareafield/widget.html
<tr>
    <td><label for="var_{{ field.name }}">{{ field.name }}</label></td>
    <td><textarea id="var_{{ field.name }}" name="_{{ field.name }}_" rows="6" cols="72">{{ field.value }}</textarea></td>
</tr>

smartsnippets/templates/smartsnippets/widgets/textfield/widget.html
<tr>
    <td><label for="var_{{ field.name }}">{{ field.name }}</label></td>
    <td><input id="var_{{ field.name }}" type="text" name="_{{ field.name }}_" value="{{ field.value }}" size="100"/></td>
</tr>